- hosts: localhost
  tasks:
    - name: Download intellij
      shell: curl --continue-at - -L https://download.jetbrains.com/idea/ideaIC-2024.1.1.tar.gz -o /tmp/idea.tar.gz

    - name: Extract intellij into /opt
      become: true
      shell: mkdir /opt/idea && tar -xzf /tmp/idea.tar.gz --strip-components 1 -C /opt/idea
