- hosts: localhost
  tasks:
    - name: Install python 3
      become: true
      apt: 
        force_apt_get: true
        update_cache: true
        pkg:
          - python3
          - ipython3 

    - name: Symlink python to python3
      become: true
      shell: ln -s /usr/bin/python3 /usr/bin/python && ln -s /usr/bin/ipython3 /usr/bin/ipython
